name: murawski
dependencies:
  - python=3.6.5
  - ipython=6.4.0
  - ipykernel=4.8.2
  - jupyter=1.0.0
  - keras=2.2.2
  - numpy=1.14.3
  - notebook=5.5.0
  - pandas=0.23.0
  - pip=10.0.1
  - scikit-learn=0.19.1
  - setuptools=39.1.0
  - tensorflow=1.9.0
  - tqdm=4.24.0
  - cython=0.28.5
  - plotly=3.1.1
  - matplotlib=2.2.3
  - joblib=0.12.2
  
  - pip:
    - xgboost
    - lightgbm